### ISSUE TITLE
Map to object broken? 

### ISSUE THREAD

**Issue by alexkli** [remy/transform#3]
Nice tool - but I cannot get map to object work in a useful way. I tried to reproduce the issue using your example:

https://transform.isthe.link/?ignore=Produce&splitter=%09&ignore=%2F%5Cd.%5Cd%5Cd%2F&strip=-%7C%5C%28%5Cd%5C%29&trim=null&dropEmpty=null&map=artist%2C+title

and this text:

```
2.12 -Huey Lewis & The News     The Power of Love
Producer - Huey Lewis & The News
3:52
2.12 -Joe Walsh     Life's Been Good
Producer - bill ssss
4:39
```

I get this:

```
{
  "artist": [],
  "title": [
    "3:52"
  ],
  "undefined": [
    "4:39"
  ]
}
```

Looks like map to object doesn't detect the (repeating) child arrays... when I first tried it on the weekend it seemed to work fine.

**Comment by remy** [comment]
Acknowledged. I changed how the rules stack so I suspect it's that.

**Comment by remy** [comment]
That's fixed.

There was also a few problems with your source content (or github swapped the tabs for spaces) and the strip matcher was a bit wrong.

Should work with this: https://transform.isthe.link/?ignore=Produce&splitter=%09&strip=%2F%28%5Cd.%5Cd%5Cd%29%7C-%2F&trim=null&dropEmpty=null&map=artist%2C+title

Plus source:

```text
2.12 -Huey Lewis & The News	The Power of Love
Producer - Huey Lewis & The News
3:52
2.12 -Joe Walsh	Life's Been Good
Producer - bill ssss
4:39
```

**Comment by alexkli** [comment]
Thanks, confirmed! I had to copy your example from the screenshot...
