### ISSUE TITLE
Site is down?

### ISSUE THREAD

**Issue by AndrewSouthpaw** [remy/transform#4]
There's a JS error on load:

![image](https://user-images.githubusercontent.com/5187404/65781114-e5e84e80-e0ff-11e9-816e-ecde9037b5d0.png)

Seems like a really cool idea though, I'd love to try it out! 😄

**Comment by remy** [comment]
Ha, it's the query string that's causing it to bork! If you remove the query string, it'll load. I'll push a patch up in the meantime.

Thanks for the report 👍

**Comment by AndrewSouthpaw** [comment]
Sure thing! I'm guessing the query string was appended from the email campaign system you were using. Thanks for pushing up a fix. 😄
